# Generated by Django 2.2.3 on 2019-07-16 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_auto_20190716_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
